### ISSUE TITLE
Support Elastic connection pooling

### ISSUE THREAD

**Issue by jayhilden** [elmahio/Elmah.Io.ElasticSearch#17]
http://nest.azurewebsites.net/elasticsearch-net/cluster-failover.html

**Comment by jayhilden** [comment]
@ThomasArdal issues #17 and #35 are mostly complete, I'd like to have all 1.2 release stories done in the next few weeks.  I'm going to be on vacation for the next week and then in London for business after that but hopefully while I'm gone @bensmind or others from my team can continue the work on this release.  When you get time can you please up the release number on team city to 1.2 so the next merge into master gets that update.

Cheers!

**Comment by ThomasArdal** [comment]
@jayhilden Awesome. I've updated to 1.2 in the nuget version.
