### ISSUE TITLE
Support for dynamic/rolling Elasticsearch indices (i.e. elmah-${yyyy.MM.dd})

### ISSUE THREAD

**Issue by codefrenzy** [elmahio/Elmah.Io.ElasticSearch#36]
It would be great if we could define an Elasticsearch index pattern like 'elmah-${yyyy.MM.dd}' and use the ErrorDocument Time property as the date to format. A nice example of this can be found in https://github.com/ReactiveMarkets/NLog.Targets.ElasticSearch. 

Is there any interest in something like this?

**Comment by ThomasArdal** [comment]
Sounds like a good idea. Having an index per day makes it faster to search across large amounts of data and easier to setup retention based on date.

@jayhilden ?

**Comment by jayhilden** [comment]
@codefrenzy and @ThomasArdal I think this is indeed a very good idea, especially since in the last release we tried to move closer to the logstash standards.

**Comment by jayhilden** [comment]
@codefrenzy I hope to have this feature plus the whole 1.2 release completed this weekened.  With any luck, you'll be able to pull down the new Nuget package on Monday

**Comment by jayhilden** [comment]
rolling indexes are now in release/1.2 branch

**Comment by jayhilden** [comment]
@codefrenzy the 1.2 release is now available on Nuget with your rolling indexes.  Enjoy!
