### ISSUE TITLE
Upgrade to NEST 2.0 binaries

### ISSUE THREAD

**Issue by jayhilden** [elmahio/Elmah.Io.ElasticSearch#49]
These have breaking changes.

https://www.elastic.co/blog/ga-release-of-nest-2-0-our-dot-net-client-for-elasticsearch

**Comment by codefrenzy** [comment]
Hi there,

Sorry, just saw this open issue. Just wondering what the status is on this? When do you think you might release your v2.0 that supports NEST 2.0?

Cheers,
Annie

**Comment by jayhilden** [comment]
@codefrenzy we are currently using the NEST 1.7.1 package which works with ElasticSearch 1.x **and** the newest ES 2.x.  My company has been running this latest release against ES 2.3 for a few months now and everything is running great.

The NEST 2.x package is **not** backwards compatible with ElasticSearch 1.x so this means that the next version of this will only work for people using ES 2.x.

The changes are probably not huge, it's just that there are breaking changing in NEST 2.x so once we upgrade the code will need to update as well.  Long story short: I don't have an ETA right now because I'm very busy at work, but if you'd like to fork the repo and make a pull request we'd love to have you as a contributor to this project!

Cheers Annie.
-Jay

**Comment by TrymBeast** [comment]
Yeah I need this too because of the dependency for Newtonsoft.Json, it only supports the version 7 and I need the 9.

If no one is planning to do it I can try to upgrade this by October, when is the next release planned?

**Comment by jayhilden** [comment]
Hey Tiago, the 2.0 release can be done by anyone with time and we can
release it whenever we are satisfied that it has been fully tested.  We're
going to need to make some notes so people know that the 2.0 version will
not be backwards compatible with the 1.x version of ES.  I talked with the
ES support guys and they strongly recommended against running the 2.0
binaries against ES 1.x.

Tiago, I'll see if I can put some time into this in the next week or two.
If you start on it let me know.

Thanks everyone!

**Comment by TrymBeast** [comment]
@jayhilden I'll be two weeks on vacations and the next one I'll probably be too busy at work, so if no work is done till than, I'll do it.

**Comment by jayhilden** [comment]
Upgrading to the Nest 2.x binaries is complete.  I need to do a bit more testing, but I hope to have a prerelease candidate available soon

**Comment by jayhilden** [comment]
@codefrenzy @TrymBeast The prerelease of version 2.0 is ready for development testing.  My company will be testing it starting in about 1 week (the start of the next release cycle).  If you'd like to try it out in development you can pull the prerelease from nuget.  

Enjoy!

https://www.nuget.org/packages/Elmah.ElasticSearch/

**Comment by jayhilden** [comment]
@codefrenzy @TrymBeast I pushed the final, 2.0.0 version to nuget just now.  Happy upgrading!

https://www.nuget.org/packages/Elmah.ElasticSearch/

**Comment by TrymBeast** [comment]
@jayhilden Thanks! I'll be upgrading real soon.
