### ISSUE TITLE
CI Build improvements

### ISSUE THREAD

**Issue by jayhilden** [elmahio/Elmah.Io.ElasticSearch#53]
1. Ensure support for .NET 4.6.1
2. Support C# 6 syntax
3. Support CI build on branches that publish -prerelease candidates to Nuget

**Comment by jayhilden** [comment]
@ThomasArdal if you'd like to switch to Appveyor that's fine, I've not used it before.  I put in the 3 things that would be nice to support.  If Appveyor is a better solution than TC I'm cool with that.

**Comment by ThomasArdal** [comment]
@jayhilden I have a build running here: https://ci.appveyor.com/project/ThomasArdal/elmah-io-elasticsearch. Maybe we should try to create a c# 6 branch or something and let Appveyor build that.

I noticed that the TeamCity project is configured to build using MSBuild for .NET 4.0. Build Tools 2015 is an option as well. Maybe swithing to that, will make it build the C# 6 code. Do you have access to the settings on TC?

**Comment by jayhilden** [comment]
@ThomasArdal this branch now has the C# 6 stuff that doesn't compile in TC.

https://github.com/elmahio/Elmah.Io.ElasticSearch/tree/feature/CSharp6

I don't have access to the TC settings, if you give me access to change the settings I can probably take care of all the items on this story.

**Comment by ThomasArdal** [comment]
@jayhilden Could you create a user here: http://teamcity.codebetter.com/? I will ask CodeBetter to add you as admin.

**Comment by jayhilden** [comment]
@ThomasArdal username is jay.hilden@gmail.com

**Comment by ThomasArdal** [comment]
@jayhilden I have asked the CodeBetter folks to add you :)

**Comment by ThomasArdal** [comment]
@jayhilden You should now have access

**Comment by jayhilden** [comment]
Thanks @ThomasArdal looks like I'm in.  I'll play a bit with TC and with AppVeyor to see which one makes the most sense.  TC is great, but the host seems really overloaded, just loading the config page takes like 30 seconds.

**Comment by jayhilden** [comment]
@ThomasArdal I've got a 2.0 RC building in Appveyor [here](https://ci.appveyor.com/project/ThomasArdal/elmah-io-elasticsearch).  The next step is to have it publish from AppVeyor to Nuget.  Is that something that you can give me rights to setup or that you would need to do?  My AppVeyor account is linked to my github account if you'd like to give me access.

Ideally this would be the configuration:
- master builds always push to nuget
- branches under the naming convention `release/*` gut pushed and tagged as "prerelease" branches.

I've tried to setup that pre-release naming convention using a `appveyor.yml` file and that indeed did work for the Appveyor build number, not sure how that exactly maps to nuget.

Thanks for the help!!

**Comment by ThomasArdal** [comment]
@jayhilden It looks like you will be able to admin all of my projects, if I add you to the team on AppVeyor. But you can specify everything in appveyor.yml and I can generate an encrypted API key in order to be able to push to NuGet.

**Comment by jayhilden** [comment]
Great, if you can get me the encrypted key I'll try it out.

**Comment by ThomasArdal** [comment]
@jayhilden I can do that. But thought about something else. Maybe I should just add you as an owner of that NuGet package. Would make sense, right? Then you can publish updates to that package as well. Using your API key and https://ci.appveyor.com/tools/encrypt.

**Comment by jayhilden** [comment]
That would be even better.  My username on nuget is
jhilden.

How about we go one step further too and remove your appveyor build and
I'll add my own. I actually already did that but I noticed that's it
picking up the changes into your project but not mine.

So 2 changes total:
1. Make jhilden an owner of the project on nuget
2. Remove the project from your appveyor account

Thanks for such a quick response.

**Comment by ThomasArdal** [comment]
@jayhilden Both done 😄

**Comment by jayhilden** [comment]
@ThomasArdal one more thing I need: I need to be an admin on this github repo so that I can add the webhooks.  I think I'm good everywhere else.

**Comment by ThomasArdal** [comment]
@jayhilden You should now be admin.

**Comment by jayhilden** [comment]
@ThomasArdal thanks Thomas, new hook is in place and working!

**Comment by jayhilden** [comment]
@ThomasArdal thank you for all your help on this.  And thank you for asking the question below about the prerelease, that took me a while to figure out.  I wish that was on stackoverflow so I could give you some points for it!

http://help.appveyor.com/discussions/problems/2626-building-prerelease-nuget-package

**Comment by ThomasArdal** [comment]
@jayhilden Always a pleasure :smile:
