### ISSUE TITLE
Environment name not used to filter errors in elmah

### ISSUE THREAD

**Issue by TrymBeast** [elmahio/Elmah.Io.ElasticSearch#58]
Hello,

I just wanted to know why the environment name is not being used to filter the errors to show on the elmah page? This is really annoying if you use the same index in the same elasticsearch cluster for different environments, but with the same application name.

**Comment by jayhilden** [comment]
@TrymBeast thanks for the feedback, I think going with your suggestion would have worked well.  The current implementation is that  "Application Name" is intended to be the globally unique, across all environments and customers.  We are doing the same thing you're doing and centralizing the error logs for multiple environments and multiple customers.  My suggestion would be to include environment name in your application name, a couple examples that we have for Application Name:
- `prod.verifybrand`
- `integration.customer1`
- `prod.customer1`
- `prod.customer2`

By including the environment name as part of the application name it should hopefully make it globally unique for you.  You can also then create some cool dashboards that bring everything together, here is an example from our production monitoring dashboard.

![image](https://cloud.githubusercontent.com/assets/6517265/15757166/ee9e686c-28c9-11e6-9609-d14afd354ca0.png)

**Comment by jayhilden** [comment]
marked as feedback, closing issue.
