### ISSUE TITLE
Elasticsearch 5.x

### ISSUE THREAD

**Issue by TrymBeast** [elmahio/Elmah.Io.ElasticSearch#74]
Hi,

Is there any plans to support Elasticsearch 5.x?

Thanks!

**Comment by BernardTheDog** [comment]
Hi, i also wanted an updated version, so i cloned the repo and fixed it myself. you can download it at https://github.com/hrmts/Elmah.Io.ElasticSearch
I also updated the packages, removed applicationinsight, made the tests run, and a few other small changes. 
now it runs with elasticsearch.net and nest version 6.2.0.
there is no nuget package out of this, so you have to compile and add it yourself.

**Comment by jayhilden** [comment]
Sorry I didn't see this message before.  If anyone wants to do a PR that would be awesome.  Updating the README with any additional instructions would be great.

My concern would be making sure that the new version worked with 2.x, 5.x, and 6.x.  Is this easy?  Is this super hard?  Maybe we don't need to as long as we do a major version bump of this project.

CC @bensmind as he may still be using the 2.x product in production

**Comment by jayhilden** [comment]
Based on my comment here in the readme, I think we can just provide a link to the current 2.x release and upgrade this release to 6.x.  If anyone needs 5.x they could make that work too.

```
Note: Release 2.0 is not compatible with ElasticSearch 1.x If you are still using 1.x then please install version 1.2.0.13 here.
```

**Comment by jayhilden** [comment]
I'm not actively maintaining this project any longer.  If you'd like to do a PR for support of NEST 6 I'd be happy to review and merge it.

**Comment by BernardTheDog** [comment]
Hi, if you see my prev. post i added a branch with version 6 here https://github.com/hrmts/Elmah.Io.ElasticSearch because i dont have time to be the maintainer of this project, and i did some changes to it that's not likely wanted for everyone else, but you are free to use it, or as @jayhilden says, to make a PR @guibranco . that would probably be the best and you would help others :)

**Comment by guibranco** [comment]
Done!
