### ISSUE TITLE
.Net 4.6 in 3.0.0.69

### ISSUE THREAD

**Issue by TrymBeast** [elmahio/Elmah.Io.ElasticSearch#77]
The latest NuGet version (3.0.0.69) includes a folder for .Net 4.6 but the assembly is targeting 4.7.2.
I have projects that target the 4.6.1 and what happens is that the package is installed but then it won't compile.

**Comment by ThomasArdal** [comment]
Fixed in [3.0.0.70](https://www.nuget.org/packages/Elmah.ElasticSearch/3.0.0.70).
